/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as JurisdicionadosRouteImport } from './routes/jurisdicionados'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalisesRouteImport } from './routes/analises'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalisesIdRouteImport } from './routes/analises.$id'
import { Route as AnaliseResponsavelRouteImport } from './routes/analise.responsavel'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const JurisdicionadosRoute = JurisdicionadosRouteImport.update({
  id: '/jurisdicionados',
  path: '/jurisdicionados',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisesRoute = AnalisesRouteImport.update({
  id: '/analises',
  path: '/analises',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisesIdRoute = AnalisesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AnalisesRoute,
} as any)
const AnaliseResponsavelRoute = AnaliseResponsavelRouteImport.update({
  id: '/analise/responsavel',
  path: '/analise/responsavel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analises': typeof AnalisesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/jurisdicionados': typeof JurisdicionadosRoute
  '/usuarios': typeof UsuariosRoute
  '/analise/responsavel': typeof AnaliseResponsavelRoute
  '/analises/$id': typeof AnalisesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analises': typeof AnalisesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/jurisdicionados': typeof JurisdicionadosRoute
  '/usuarios': typeof UsuariosRoute
  '/analise/responsavel': typeof AnaliseResponsavelRoute
  '/analises/$id': typeof AnalisesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analises': typeof AnalisesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/jurisdicionados': typeof JurisdicionadosRoute
  '/usuarios': typeof UsuariosRoute
  '/analise/responsavel': typeof AnaliseResponsavelRoute
  '/analises/$id': typeof AnalisesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analises'
    | '/dashboard'
    | '/jurisdicionados'
    | '/usuarios'
    | '/analise/responsavel'
    | '/analises/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analises'
    | '/dashboard'
    | '/jurisdicionados'
    | '/usuarios'
    | '/analise/responsavel'
    | '/analises/$id'
  id:
    | '__root__'
    | '/'
    | '/analises'
    | '/dashboard'
    | '/jurisdicionados'
    | '/usuarios'
    | '/analise/responsavel'
    | '/analises/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalisesRoute: typeof AnalisesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  JurisdicionadosRoute: typeof JurisdicionadosRoute
  UsuariosRoute: typeof UsuariosRoute
  AnaliseResponsavelRoute: typeof AnaliseResponsavelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jurisdicionados': {
      id: '/jurisdicionados'
      path: '/jurisdicionados'
      fullPath: '/jurisdicionados'
      preLoaderRoute: typeof JurisdicionadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analises': {
      id: '/analises'
      path: '/analises'
      fullPath: '/analises'
      preLoaderRoute: typeof AnalisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analises/$id': {
      id: '/analises/$id'
      path: '/$id'
      fullPath: '/analises/$id'
      preLoaderRoute: typeof AnalisesIdRouteImport
      parentRoute: typeof AnalisesRoute
    }
    '/analise/responsavel': {
      id: '/analise/responsavel'
      path: '/analise/responsavel'
      fullPath: '/analise/responsavel'
      preLoaderRoute: typeof AnaliseResponsavelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AnalisesRouteChildren {
  AnalisesIdRoute: typeof AnalisesIdRoute
}

const AnalisesRouteChildren: AnalisesRouteChildren = {
  AnalisesIdRoute: AnalisesIdRoute,
}

const AnalisesRouteWithChildren = AnalisesRoute._addFileChildren(
  AnalisesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalisesRoute: AnalisesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  JurisdicionadosRoute: JurisdicionadosRoute,
  UsuariosRoute: UsuariosRoute,
  AnaliseResponsavelRoute: AnaliseResponsavelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
