/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AutuacaoRouteImport } from './routes/autuacao'
import { Route as AnalisesRouteImport } from './routes/analises'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnaliseResponsavelRouteImport } from './routes/analise.responsavel'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AutuacaoRoute = AutuacaoRouteImport.update({
  id: '/autuacao',
  path: '/autuacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisesRoute = AnalisesRouteImport.update({
  id: '/analises',
  path: '/analises',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseResponsavelRoute = AnaliseResponsavelRouteImport.update({
  id: '/analise/responsavel',
  path: '/analise/responsavel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analises': typeof AnalisesRoute
  '/autuacao': typeof AutuacaoRoute
  '/dashboard': typeof DashboardRoute
  '/analise/responsavel': typeof AnaliseResponsavelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analises': typeof AnalisesRoute
  '/autuacao': typeof AutuacaoRoute
  '/dashboard': typeof DashboardRoute
  '/analise/responsavel': typeof AnaliseResponsavelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analises': typeof AnalisesRoute
  '/autuacao': typeof AutuacaoRoute
  '/dashboard': typeof DashboardRoute
  '/analise/responsavel': typeof AnaliseResponsavelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analises'
    | '/autuacao'
    | '/dashboard'
    | '/analise/responsavel'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analises' | '/autuacao' | '/dashboard' | '/analise/responsavel'
  id:
    | '__root__'
    | '/'
    | '/analises'
    | '/autuacao'
    | '/dashboard'
    | '/analise/responsavel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalisesRoute: typeof AnalisesRoute
  AutuacaoRoute: typeof AutuacaoRoute
  DashboardRoute: typeof DashboardRoute
  AnaliseResponsavelRoute: typeof AnaliseResponsavelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autuacao': {
      id: '/autuacao'
      path: '/autuacao'
      fullPath: '/autuacao'
      preLoaderRoute: typeof AutuacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analises': {
      id: '/analises'
      path: '/analises'
      fullPath: '/analises'
      preLoaderRoute: typeof AnalisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise/responsavel': {
      id: '/analise/responsavel'
      path: '/analise/responsavel'
      fullPath: '/analise/responsavel'
      preLoaderRoute: typeof AnaliseResponsavelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalisesRoute: AnalisesRoute,
  AutuacaoRoute: AutuacaoRoute,
  DashboardRoute: DashboardRoute,
  AnaliseResponsavelRoute: AnaliseResponsavelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
